CREATE  TABLE IF NOT EXISTS `managers` (
`man_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`is_admin` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
`firstname` VARCHAR(50) NOT NULL,
`lastname` VARCHAR(50) NOT NULL,
`username` VARCHAR(40) NOT NULL,
`password` VARCHAR(40) NOT NULL,
`group_id` INT(11) UNSIGNED NOT NULL,
`ip` VARCHAR(50),
`email` VARCHAR(50) NOT NULL,
`icq` VARCHAR(9),
`skype` VARCHAR(15) COLLATE 'utf8_bin' NOT NULL,
`telephone` VARCHAR(10) COLLATE 'utf8_bin' NOT NULL,
`dobav` SMALLINT(11) UNSIGNED,
`order_type` VARCHAR(20) NOT NULL,
`is_senior` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Administrator office',
`win_login` VARCHAR(30) COLLATE 'utf8_bin' COMMENT 'Windows auth',
`status` ENUM('online','offline','away','auto_away','lunch','busy') NOT NULL,
`last_online_time` DATETIME,
`stat` TINYINT(6) UNSIGNED NOT NULL,
`bind_to` ENUM('partner','firm'),
`bind_id` INT(11) UNSIGNED,
`control_type` ENUM('white_list','none'),
`visible` ENUM('all','crm','none') NOT NULL DEFAULT 'all',
`mailcontroller` TINYINT(1) NOT NULL DEFAULT '0',
`rss_pass` VARCHAR(32) COLLATE 'utf8_bin' NOT NULL COMMENT 'auth on rss script',
`description` VARCHAR(512) COLLATE 'utf8_bin',
`is_deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
`create_time` TIMESTAMP,
PRIMARY KEY (`man_id`),
UNIQUE INDEX `dobav` (`dobav` ASC),
INDEX `group_id` (`group_id` ASC),
INDEX `status` (`status` ASC),
INDEX `username` (`username` ASC),
INDEX `password` (`password`(10) ASC),
INDEX `stat` (`stat` ASC),
INDEX `visible` (`visible` ASC),
INDEX `mailcontroller` (`mailcontroller` ASC),
INDEX `win_login` (`win_login` ASC) ,
CONSTRAINT `fk_managers__group_id`
FOREIGN KEY (`group_id`)
REFERENCES `managers_groups` (`group_id`))
ENGINE = InnoDB;