CREATE  TABLE IF NOT EXISTS `managers_groups` (
`group_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`group_name` VARCHAR(50) NOT NULL,
`dobav` SMALLINT(11) UNSIGNED NULL DEFAULT NULL,
`status` TINYINT(11) UNSIGNED NOT NULL ,
`control_type` ENUM('none','white_list','hash') NOT NULL ,
`visible` ENUM('all','crm','none') NOT NULL DEFAULT 'none' ,
`skype` VARCHAR(20) COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
`icq` VARCHAR(9) NOT NULL DEFAULT '',
`email` VARCHAR(30) NOT NULL DEFAULT '',
`telephone` VARCHAR(50) NOT NULL DEFAULT '',
`senior_man_id` INT(11) UNSIGNED NULL DEFAULT NULL ,
`adress_id` INT(11) UNSIGNED NULL DEFAULT NULL ,
`telephone_id` INT(11) UNSIGNED NULL DEFAULT NULL ,
`parent` INT(11) UNSIGNED NULL DEFAULT NULL ,
`sort_order` TINYINT(4) NULL DEFAULT '-1' ,
`type` ENUM('manager','partner','courier','management') NOT NULL DEFAULT 'manager' ,
PRIMARY KEY (`group_id`) ,
INDEX `visible` (`visible` ASC) ,
INDEX `telephone_id` (`telephone_id` ASC) )
ENGINE = InnoDB;