CREATE  TABLE IF NOT EXISTS `sotm_product_status` (
`product_status_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Идентификатор статуса',
`status_code` VARCHAR(16) NOT NULL DEFAULT '' COMMENT 'Код статуса',
`title` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Название статуса',
`display_in_product_list` TINYINT(1) NOT NULL DEFAULT '1' COMMENT 'Признак \"Отображать в списке товаров\"',
`display_in_product_page` TINYINT(1) NOT NULL DEFAULT '1' COMMENT 'Признак \"Отображать в списке товаров\"',
`product_status_order` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Порядок сортировки',
`seo_mark_correction` TINYINT(4) NULL DEFAULT '0',
`seo_status_id` INT(11) UNSIGNED NOT NULL DEFAULT '1' COMMENT 'Идентификатор SEO статуса сопостовимого со статусом товара',
`is_product_published` TINYINT(1) NOT NULL DEFAULT '1' COMMENT 'Признак публикации продукта в статусе',
`is_edited` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Признак \"Запись редактирована\"',
`date_modified` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Дата модификации записи',
`is_deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Признак \"Запись удалена\"',
`date_deleted` TIMESTAMP   COMMENT 'Дата удаления записи',
`seo_mark_correction1` TINYINT(4) NOT NULL DEFAULT '0',
PRIMARY KEY (`product_status_id`),
UNIQUE INDEX `indx_status_code` (`status_code` ASC),
INDEX `indx_display_in_product_list` (`display_in_product_list` ASC),
INDEX `indx_status_display_order` (`display_in_product_list` ASC, `product_status_order` ASC),
INDEX `product_status_order` (`product_status_order` ASC) )
ENGINE = InnoDB;